unit_tests:
stage: test
script: 
- npm ci
- npm test
artifacts:
  when:always
reports:
  junit: reports/junit.xml

netlify:
image: node:22-alpine
 stage: .pre
variables:
 NETLIFY_SITE_ID: '9ff9b087-22b9-4146-931d-5c5622e0261d'
script: 
	- npm install -g netlify-cli
	- netlify --version
	- echo "Deploying to the site id $NETLIFY_SITE_ID"
 
 
